// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SwRK3Zs2VAwQPq51MWvNmv9U47sVGMo',
    appId: '1:162605286658:android:c6418d2553ff16cab16e1b',
    messagingSenderId: '162605286658',
    projectId: 'minimal-chat-app-2e8ec',
    storageBucket: 'minimal-chat-app-2e8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKEUzEp9BFNrAkt7RtKsDkdBhx2tXecGE',
    appId: '1:162605286658:ios:5439607f55bd58bbb16e1b',
    messagingSenderId: '162605286658',
    projectId: 'minimal-chat-app-2e8ec',
    storageBucket: 'minimal-chat-app-2e8ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKEUzEp9BFNrAkt7RtKsDkdBhx2tXecGE',
    appId: '1:162605286658:ios:5439607f55bd58bbb16e1b',
    messagingSenderId: '162605286658',
    projectId: 'minimal-chat-app-2e8ec',
    storageBucket: 'minimal-chat-app-2e8ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
